name: linstant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  crypto: ^3.0.3
  email_validator: ^2.1.17
  firebase_auth: ^4.17.8
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.6.0
  google_fonts: ^6.2.0
  transparent_image: ^2.0.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/linstant_logo.png
    - assets/images/x_icon.png
    - assets/images/facebook_icon.png
    - assets/images/instagram_icon.png
    - assets/images/snapchat_icon.png
    - assets/images/register_background.png
  
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans.ttf




